### ISSUE TITLE
Markdown links only open if the cursor is on the url itself

### ISSUE THREAD

**Issue by piersolenski** [chrishrb/gx.nvim#12]
I'm not sure if this is intentional, but currently markdown links only open if the cursor is over the url itself, rather than if it is anywhere within the boundaries of the markdown link syntax. It would be awesome if you could open the link wherever the cursor is placed, especially for longer worded links, and with url concealing being a feature!

```
[gx does nothing here](https://www.gx-works-here.com/).
```

**Comment by chrishrb** [comment]
thanks for this suggestion. This should work now properly 👍
