### ISSUE TITLE
Allow for user defined handlers

### ISSUE THREAD

**Issue by reegnz** [chrishrb/gx.nvim#36]
As a plugin user I'd appreciate it if gx.nvim would allow for defining my own handlers, in good old gx-extended fashion.

**Comment by dsully** [comment]
+1 - I'd love to be able to add `--background` to `open` if I'm on `macOS` for example.

**Comment by chrishrb** [comment]
I saw that @ChristianMoesl forked and already implemented this feature. Is this ready to merge?

**Comment by ChristianMoesl** [comment]
@chrishrb I had a second look at my changes, polished them a bit and created a PR. I also took the liberty to refactor a bit. Let me know what you think!

**Comment by chrishrb** [comment]
Again, big thanks for this PR. Refactorings also look good to me and make sense 👍 

Resolved in #49
