### ISSUE TITLE
Weird text after gx

### ISSUE THREAD

**Issue by darkangel-ua** [chrishrb/gx.nvim#4]
Not sure what is happening but when I press `gx` over any link I'm getting this thing on my screen:
![image](https://user-images.githubusercontent.com/1231653/227707868-6afb90b1-d3a8-450b-b01e-7f71eeff2024.png)

**Comment by chrishrb** [comment]
hm this seems to be also a linux issue, i'm working on it

**Comment by chrishrb** [comment]
should be solved now, if the issue still exists reopen this issue 👍
