### ISSUE TITLE
[feature request] add jump to file

### ISSUE THREAD

**Issue by shellRaining** [chrishrb/gx.nvim#43]
thanks for your useful plugin first! Nowadays I encounter this situation

```
Error: error occured in dts build
    at Worker.<anonymous> (/Users/shellraining/Documents/learnsth/vitepress/sugar-blog/node_modules/.pnpm/tsup@7.2.0_typescript@5.1.6/node_modules/tsup/dist/index.js:2294:26)
```

when I press gf, it not jump beacuse `:2294:26`, can you enhance this plugin to support?

**Comment by chrishrb** [comment]
But jump to file is not part of this plugin? Or what do you mean?

**Comment by shellRaining** [comment]
Yes, I feel that jumping to files is indeed not very consistent with the functionality of gx.nvim, but there is also no similar gf.nvim 😢

**Comment by chrishrb** [comment]
Jumping to files is NOT implemented, and it's not something this feature should do. Additionally, I don’t have any problems with the default `gf` command.
