### ISSUE TITLE
can't open link when read docs

### ISSUE THREAD

**Issue by shellRaining** [chrishrb/gx.nvim#59]
<img width="981" alt="image" src="https://github.com/chrishrb/gx.nvim/assets/111564053/86bdf979-c3ca-402d-8838-15cb6e5da5cc">

when I press K to view docs, and move cursor to a link, then press gx, nothing has happened. Is this a bug or ?

**Comment by chrishrb** [comment]
hm.. for me this works. what version of nvim and gx.nvim are you using?

**Comment by shellRaining** [comment]
It feels strange, I used to encounter this issue when I was using `noice.nvim`, but now that I've removed the plugin, it's gone.
