### ISSUE TITLE
gx.nvim doesn't respect fragments in URLs

### ISSUE THREAD

**Issue by hatredholder** [chrishrb/gx.nvim#6]
Whenever you try to open a URL with a fragment (a hash sign #)  **gx.nvim** opens it without the fragment in it.

Here's an example for clarity:

A URL like: 
```https://flask.palletsprojects.com/en/2.2.x/testing/#tests-that-depend-on-an-active-context``` 

**gx.nvim** opens as: 
```https://flask.palletsprojects.com/en/2.2.x/testing/```

**Comment by chrishrb** [comment]
should work now, if you still have this issue, please reopen this issue 👍

**Comment by hatredholder** [comment]
> should work now, if you still have this issue, please reopen this issue 

It's fixed, much love to you :heart:
